-- Create mpa_rating table first
CREATE TABLE IF NOT EXISTS mpa_rating (
    rating_id INT PRIMARY KEY,
    name VARCHAR(10) NOT NULL UNIQUE
);

-- Create genres table
CREATE TABLE IF NOT EXISTS genres (
    genre_id INT PRIMARY KEY,
    genre_name VARCHAR(255) NOT NULL UNIQUE
);

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    birthday DATE NOT NULL,
    CONSTRAINT uk_email UNIQUE (email),
    CONSTRAINT uk_login UNIQUE (login)
);

-- Таблица фильмов (теперь rating_id имеет тип INT)
CREATE TABLE IF NOT EXISTS films (
    film_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    release_date DATE NOT NULL,
    duration INT NOT NULL,
    rating_id INT NOT NULL,
    FOREIGN KEY (rating_id) REFERENCES mpa_rating(rating_id)
);

-- Таблица дружбы (односторонняя)
CREATE TABLE IF NOT EXISTS users_friends (
    user_id INT NOT NULL,
    friend_id INT NOT NULL,
    status VARCHAR(20) DEFAULT 'unconfirmed',
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uk_friendship UNIQUE (user_id, friend_id)
);

-- Таблица лайков фильмов
CREATE TABLE IF NOT EXISTS users_likes (
    user_id INT NOT NULL,
    film_id INT NOT NULL,
    PRIMARY KEY (user_id, film_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE
);

-- Таблица жанров фильмов
CREATE TABLE IF NOT EXISTS film_genres (
    film_id INT NOT NULL,
    genre_id INT NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres(genre_id) ON DELETE CASCADE
);

-- Индексы
CREATE INDEX IF NOT EXISTS idx_friendships_user_id ON users_friends (user_id);
CREATE INDEX IF NOT EXISTS idx_friendships_friend_id ON users_friends (friend_id);
CREATE INDEX IF NOT EXISTS idx_films_rating_id ON films (rating_id);
CREATE INDEX IF NOT EXISTS idx_film_likes_film_id ON users_likes (film_id);
CREATE INDEX IF NOT EXISTS idx_film_likes_user_id ON users_likes (user_id);
CREATE INDEX IF NOT EXISTS idx_film_genres_film_id ON film_genres (film_id);
CREATE INDEX IF NOT EXISTS idx_film_genres_genre_id ON film_genres (genre_id);

-- Add an index for faster lookups (optional but recommended)
CREATE INDEX IF NOT EXISTS idx_users_likes_user_id ON users_likes (user_id);
CREATE INDEX IF NOT EXISTS idx_users_likes_film_id ON users_likes (film_id);